[package]
name = "galacritty"
version = "0.1.0"
authors = ["Daniel Svensson <dsvensson@gmail.com>"]
edition = "2018"
license-file = "LICENSE.md"

[dependencies]
gtk = { version = "0.8", features = ["v3_20"] }
glib = "0.9"
relm = "0.19"
relm-derive = "0.19"
